//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.04 at 04:45:59 PM PDT 
//


package com.senecasoap.soap.factory;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.senecasoap.soap.factory package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.senecasoap.soap.factory
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateCustomerResponse }
     * 
     */
    public UpdateCustomerResponse createUpdateCustomerResponse() {
        return new UpdateCustomerResponse();
    }

    /**
     * Create an instance of {@link NewCustomerResponse }
     * 
     */
    public NewCustomerResponse createNewCustomerResponse() {
        return new NewCustomerResponse();
    }

    /**
     * Create an instance of {@link SalesDetailsRequest }
     * 
     */
    public SalesDetailsRequest createSalesDetailsRequest() {
        return new SalesDetailsRequest();
    }

    /**
     * Create an instance of {@link ListProductRequest }
     * 
     */
    public ListProductRequest createListProductRequest() {
        return new ListProductRequest();
    }

    /**
     * Create an instance of {@link NewCustomerRequest }
     * 
     */
    public NewCustomerRequest createNewCustomerRequest() {
        return new NewCustomerRequest();
    }

    /**
     * Create an instance of {@link NewProductRequest }
     * 
     */
    public NewProductRequest createNewProductRequest() {
        return new NewProductRequest();
    }

    /**
     * Create an instance of {@link ListProductResponse }
     * 
     */
    public ListProductResponse createListProductResponse() {
        return new ListProductResponse();
    }

    /**
     * Create an instance of {@link ProductSoap }
     * 
     */
    public ProductSoap createProductSoap() {
        return new ProductSoap();
    }

    /**
     * Create an instance of {@link SalesDetailsResponse }
     * 
     */
    public SalesDetailsResponse createSalesDetailsResponse() {
        return new SalesDetailsResponse();
    }

    /**
     * Create an instance of {@link SaleSoap }
     * 
     */
    public SaleSoap createSaleSoap() {
        return new SaleSoap();
    }

    /**
     * Create an instance of {@link UpdateCustomerRequest }
     * 
     */
    public UpdateCustomerRequest createUpdateCustomerRequest() {
        return new UpdateCustomerRequest();
    }

    /**
     * Create an instance of {@link NewProductResponse }
     * 
     */
    public NewProductResponse createNewProductResponse() {
        return new NewProductResponse();
    }

    /**
     * Create an instance of {@link SalesRepSoap }
     * 
     */
    public SalesRepSoap createSalesRepSoap() {
        return new SalesRepSoap();
    }

    /**
     * Create an instance of {@link CustomerSoap }
     * 
     */
    public CustomerSoap createCustomerSoap() {
        return new CustomerSoap();
    }

    /**
     * Create an instance of {@link TimeSoap }
     * 
     */
    public TimeSoap createTimeSoap() {
        return new TimeSoap();
    }

}
