//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.04 at 04:45:59 PM PDT 
//


package com.senecasoap.soap.factory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SaleSoap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SaleSoap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customer" type="{http://www.senecasoap.com/soap/factory}CustomerSoap"/>
 *         &lt;element name="product" type="{http://www.senecasoap.com/soap/factory}ProductSoap"/>
 *         &lt;element name="salesRep" type="{http://www.senecasoap.com/soap/factory}SalesRepSoap"/>
 *         &lt;element name="time" type="{http://www.senecasoap.com/soap/factory}TimeSoap"/>
 *         &lt;element name="salesAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaleSoap", propOrder = {
    "customer",
    "product",
    "salesRep",
    "time",
    "salesAmount"
})
public class SaleSoap {

    @XmlElement(required = true)
    protected CustomerSoap customer;
    @XmlElement(required = true)
    protected ProductSoap product;
    @XmlElement(required = true)
    protected SalesRepSoap salesRep;
    @XmlElement(required = true)
    protected TimeSoap time;
    protected double salesAmount;

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerSoap }
     *     
     */
    public CustomerSoap getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerSoap }
     *     
     */
    public void setCustomer(CustomerSoap value) {
        this.customer = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSoap }
     *     
     */
    public ProductSoap getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSoap }
     *     
     */
    public void setProduct(ProductSoap value) {
        this.product = value;
    }

    /**
     * Gets the value of the salesRep property.
     * 
     * @return
     *     possible object is
     *     {@link SalesRepSoap }
     *     
     */
    public SalesRepSoap getSalesRep() {
        return salesRep;
    }

    /**
     * Sets the value of the salesRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesRepSoap }
     *     
     */
    public void setSalesRep(SalesRepSoap value) {
        this.salesRep = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSoap }
     *     
     */
    public TimeSoap getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSoap }
     *     
     */
    public void setTime(TimeSoap value) {
        this.time = value;
    }

    /**
     * Gets the value of the salesAmount property.
     * 
     */
    public double getSalesAmount() {
        return salesAmount;
    }

    /**
     * Sets the value of the salesAmount property.
     * 
     */
    public void setSalesAmount(double value) {
        this.salesAmount = value;
    }

}
